# Generated by Django 5.1.1 on 2024-10-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_place_created_at_alter_place_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='place',
            name='updated_at',
        ),
    ]
