# Generated by Django 5.1.1 on 2024-10-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_remove_place_created_at_remove_place_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['id']},
        ),
    ]
