# Generated by Django 5.1.1 on 2024-10-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_place_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
    ]
